### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by simoneVU** [LoveCatc/supervised-llm-uncertainty-estimation#3]
Really interesting paper! I was interested in whether you have in plan to release the model weights for random forest any soon.

Thank you!

**Comment by ly-liu15** [comment]
Thank you for your kind words! 

For each LLM model, each feature selection way (middle layer/last layer, question/answer, average/last token), and each dataset, we should train a random forest model, so the total number of models is large. That's the reason we don't plan to release the model weights here. 

But in line 214-237 of `supervised_calibration.py`, we provide the hyperparameters of the random forest model including the random state, so the weights are available if you can use them to train it.

**Comment by simoneVU** [comment]
Thank you very much for the quick response!
