### ISSUE TITLE
Unable to generate the required files

### ISSUE THREAD

**Issue by learningfromscratch21** [LoveCatc/supervised-llm-uncertainty-estimation#6]
Hello again,

I am trying to generate the required files from generate-ds and train-supervised.
When I execute generate-ds coqa related files are not getting generated and with train-supervised I am Unable to generate "test_output/ask4conf/gemma_7b/triviaqa__triviaqa__train.jsonl" when I ran the code "CUDA_VISIBLE_DEVICES=7,8 python run.py train-supervised -m gemma_7b -d triviaqa" it generatd <>.__test.jsonl. How do I generate the required files?

I am using 4 V100-SXM3-32GB GPUs. Could you please help me in getting the repository up and running.

**Comment by LoveCatc** [comment]
Sorry for the late response, busy last week. Could you please share your error message?

**Comment by learningfromscratch21** [comment]
Hello,
I can understand.
![image](https://github.com/user-attachments/assets/6afd8b7b-fd3b-46ab-bf2a-af474c320e76)
![image](https://github.com/user-attachments/assets/2ca79725-12d8-415a-b48c-64cd180b85a7)

Above are the error screen shots. I have followed the instructions from Readme. Data is generated for coqa but when i execute generate-ds it gives a warning.

**Comment by LoveCatc** [comment]
This is weird. It seems you are not only failing to generate triviaqa but also coqa, which are the default option of `generate_ds`. The problem with coqa should be the `formatter` failed to find key `id`, which I would check this afternoon. Could you please also add the debug info of triviaqa? Failures at `generate_ds` should produce two lines of warnings, but I only see one.
P.S. Something seems wrong with my github email notification. Sorry for the late response again :X

**Comment by learningfromscratch21** [comment]
Thank you for checking.
below is the screenshot of similar error for llama_3_8b
![image](https://github.com/user-attachments/assets/91db54bc-dd08-4f06-8f3f-6cdea8b15c05)
I can see that its failing for all 3 models gemma_7b,  llama_3_8b, Llama-2-7b-hf-local.
I hope this helps.

**Comment by LoveCatc** [comment]
Hi, I have checked the causes of the issue and there are two bugs preventing the data from correctly generating. The first is quite a coincidence, as we used `EleutherAI/coqa` dataset as coqa source when we did the experiments, but I wrote the `stanfordnlp/coqa` in the config file which does not contain a valid `id` key. That is why you see a stange warning said "id". Unfortunately, it seems the original EleutherAI repo has some problem and does not work properly now, so I have rewritten a coqa_formatter and updated in the latest master branch. The second problem seems to be due to the missing of padding token. I am not sure why this would happen as we should not include any padding operation in our code. But I still handled this case and set the pad_token to eos if it does not have one. You can now try to pull the latest code, **delete the `data_cache` directory**, and rerun the generation. If there is still any problem, please add in this issue.

**Comment by fancy-chenyao** [comment]
![image](https://github.com/user-attachments/assets/df1e2972-9445-4546-b2e6-99f5265444f2)
Hello, may I ask if this is a successful build or a failure. If it fails, how can I build it successfully?

**Comment by LoveCatc** [comment]
It still seems to be a failure. I will check again and reply soon.

**Comment by LoveCatc** [comment]
Hi @fancy-chenyao, I have updated `generate_ds` and provided a finer exception handling. Could you please pull the latest code and run the script again? Also please tell me the command you are using.

**Comment by fancy-chenyao** [comment]
The command I am trying to execute is: python run.py generate-ds. I just pulled the latest run.py code, and a new exception still occurred when executing generate-ds.
![image](https://github.com/user-attachments/assets/2ac51885-1933-4eeb-9763-2989924ce5f6)

**Comment by fancy-chenyao** [comment]
> Hi @fancy-chenyao, I have updated `generate_ds` and provided a finer exception handling. Could you please pull the latest code and run the script again? Also please tell me the command you are using.

![image](https://github.com/user-attachments/assets/9491dddc-149d-47df-83f8-2b121c879d96)
Hello, the problem comes from here. d[Q_END] is printed as double type. Can I just convert it to int type directly? Will this modification affect my subsequent work?

**Comment by fancy-chenyao** [comment]
![image](https://github.com/user-attachments/assets/2bcec177-2883-42a0-85b2-83aa86d119b1)
After the above modifications, new problems appeared. How to solve the noneType situation? I look forward to your reply!

**Comment by LoveCatc** [comment]
I am really sorry that I did not get any issue notifications in my email. If you still have any problems, please directly leave your email and I will send you my contact info so that we can communicate more conveniently.

**Comment by LoveCatc** [comment]
Feel free to open a new one if you have any issues.
