### ISSUE TITLE
How to generate the file "'test_output/ask4conf/llama_3_8b/triviaqa__triviaqa__test.jsonl'"

### ISSUE THREAD

**Issue by fancy-chenyao** [LoveCatc/supervised-llm-uncertainty-estimation#7]
Hi, thank you so much for sharing your work! I am very interested in your work. When I reproduced your work, I did not generate the file ''test_output/ask4conf/llama_3_8b/triviaqa__triviaqa__test.jsonl''. In what step was this file generated?

**Comment by LoveCatc** [comment]
I am really sorry that I did not get any issue notifications in my email. If you still have any problems, please directly leave your email and I will send you my contact info so that we can communicate more conveniently.

**Comment by LoveCatc** [comment]
Feel free to open a new one if you have any issues. If I do not reply, write an email to py4contact@gmail.com.
